"""
    Swagger Words
    ~~~~~~~~~~~~~

    Python friendly aliases to reserved Swagger words.

    :copyright: Copyright 2018 PlanGrid, Inc., see AUTHORS.
    :license: MIT, see LICENSE for details.
"""
from __future__ import unicode_literals

additional_properties = 'additionalProperties'
all_of = 'allOf'
allow_empty_value = 'allowEmptyValue'
api_key = 'apiKey'
array = 'array'
basic = 'basic'
binary = 'binary'
body = 'body'
boolean = 'boolean'
byte = 'byte'
collection_format = 'collectionFormat'
components = 'components'
consumes = 'consumes'
contact = 'contact'
csv = 'csv'
delete = 'delete'
date = 'date'
date_time = 'date-time'
default = 'default'
definitions = 'definitions'
description = 'description'
double = 'double'
email = 'email'
enum = 'enum'
exclusive_maximum = 'exclusiveMaximum'
exclusive_minimum = 'exclusiveMinimum'
external_docs = 'externalDocs'
float_ = 'float'
format_ = 'format'
get = 'get'
head = 'head'
header = 'header'
host = 'host'
in_ = 'in'
info = 'info'
integer = 'integer'
int32 = 'int32'
int64 = 'int64'
items = 'items'
license_ = 'license'
max_items = 'maxItems'
max_length = 'maxLength'
max_properties = 'maxProperties'
maximum = 'maximum'
min_items = 'minItems'
min_length = 'minLength'
min_properties = 'minProperties'
minimum = 'minimum'
multi = 'multi'
multiple_of = 'multipleOf'
name = 'name'
nullable = 'x-nullable'
number = 'number'
oauth2 = 'oauth2'
object_ = 'object'
openapi = 'openapi'
operation_id = 'operationId'
options = 'options'
parameters = 'parameters'
password = 'password'
patch = 'patch'
path = 'path'
paths = 'paths'
pattern = 'pattern'
post = 'post'
produces = 'produces'
properties = 'properties'
put = 'put'
query = 'query'
ref = '$ref'
required = 'required'
responses = 'responses'
schema = 'schema'
schemes = 'schemes'
security = 'security'
security_definitions = 'securityDefinitions'
servers = 'servers'
string = 'string'
summary = 'summary'
swagger = 'swagger'
tags = 'tags'
terms_of_service = 'termsOfService'
title = 'title'
trace = 'trace'
type_ = 'type'
unique_items = 'uniqueItems'
url = 'url'
uuid = 'uuid'
version = 'version'
