[tool.black]
exclude = '''
/(
    \.pytest_cache
  | \.git
  | \.venv
)/
'''

[tool.pytest.ini_options]
filterwarnings = [
    "error"
]

[build-system]
requires = [
    "setuptools >= 35.0.2",
]
build-backend = "setuptools.build_meta"
