#!/usr/bin/env python3
import subprocess


if __name__ == "__main__":
    try:
        subprocess.check_output(["black", "--check", "--diff", "."])
    except subprocess.CalledProcessError as e:
        if e.returncode == 1:
            print(e.stdout.decode("utf-8"))
    # proc = subprocess.run(["black", "--check", "--diff", "."])

    # if proc.returncode == 0:
    #     print("This code is black!")
    # else:
    #     print("This code is not black. Here's what's wrong:")
    #     print(proc.stdout)
