additional_properties = 'additionalProperties'
all_of = 'allOf'
allow_empty_value = 'allowEmptyValue'
collection_format = 'collectionFormat'
default = 'default'
description = 'description'
enum = 'enum'
exclusive_maximum = 'exclusiveMaximum'
exclusive_minimum = 'exclusiveMinimum'
format_ = 'format'
in_ = 'in'
items = 'items'
max_items = 'maxItems'
max_length = 'maxLength'
max_properties = 'maxProperties'
maximum = 'maximum'
min_items = 'minItems'
min_length = 'minLength'
min_properties = 'minProperties'
minimum = 'minimum'
multiple_of = 'multipleOf'
name = 'name'
pattern = 'pattern'
properties = 'properties'
ref = '$ref'
required = 'required'
schema = 'schema'
title = 'title'
type_ = 'type'
unique_items = 'uniqueItems'
nullable = 'x-nullable'

array = 'array'
boolean = 'boolean'
integer = 'integer'
number = 'number'
string = 'string'
object_ = 'object'

date_time = 'date-time'
date = 'date'
uuid = 'uuid'

multi = 'multi'
csv = 'csv'

query = 'query'
body = 'body'
path = 'path'
header = 'header'

swagger = 'swagger'
host = 'host'
produces = 'produces'
consumes = 'consumes'
info = 'info'
paths = 'paths'
definitions = 'definitions'
schemes = 'schemes'
parameters = 'parameters'
operation_id = 'operationId'
responses = 'responses'
security = 'security'
security_definitions = 'securityDefinitions'

api_key = 'apiKey'
basic = 'basic'
oauth2 = 'oauth2'
